import UserProps from "../service/interfaces/User";

export const fakeUsers: UserProps[] = [
    {
        userId: 1,
        name: "Ana Souza",
        avatarUrl: "https://i.pravatar.cc/150?img=1",
        revenue: 15840,
        salesCount: 132,
        position: 1,
        isCurrentUser: false,
    },
    {
        userId: 2,
        name: "Carlos Mendes",
        avatarUrl: "https://i.pravatar.cc/150?img=2",
        revenue: 14210,
        salesCount: 118,
        position: 2,
        isCurrentUser: false,
    },
    {
        userId: 3,
        name: "Juliana Rocha",
        avatarUrl: "https://i.pravatar.cc/150?img=3",
        revenue: 12890,
        salesCount: 101,
        position: 3,
        isCurrentUser: false,
    },
    {
        userId: 4,
        name: "Pedro Lima",
        avatarUrl: "https://i.pravatar.cc/150?img=4",
        revenue: 10950,
        salesCount: 87,
        position: 4,
        isCurrentUser: false,
    },
    {
        userId: 5,
        name: "Você",
        avatarUrl: "https://i.pravatar.cc/150?img=5",
        revenue: 8450,
        salesCount: 64,
        position: 5,
        isCurrentUser: true,
    },
    {
        userId: 6,
        name: "Marina Costa",
        avatarUrl: "https://i.pravatar.cc/150?img=6",
        revenue: 7920,
        salesCount: 59,
        position: 6,
        isCurrentUser: false,
    },
    {
        userId: 7,
        name: "Rafael Nogueira",
        avatarUrl: "https://i.pravatar.cc/150?img=7",
        revenue: 6890,
        salesCount: 51,
        position: 7,
        isCurrentUser: false,
    },
    {
        userId: 8,
        name: "Fernanda Alves",
        avatarUrl: "https://i.pravatar.cc/150?img=8",
        revenue: 5540,
        salesCount: 43,
        position: 8,
        isCurrentUser: false,
    },
    {
        userId: 9,
        name: "Lucas Pereira",
        avatarUrl: "https://i.pravatar.cc/150?img=9",
        revenue: 4310,
        salesCount: 31,
        position: 9,
        isCurrentUser: false,
    },
    {
        userId: 10,
        name: "Beatriz Santos",
        avatarUrl: "https://i.pravatar.cc/150?img=10",
        revenue: 2890,
        salesCount: 19,
        position: 10,
        isCurrentUser: false,
    },
];